import { Link, Image } from "@utils/packages"

export const metadata = {
  title: 'Authentications',
  description: 'Generated by create next app',
}

export default function AuthenticationLayout({ children }) {
  return (
    <section className="auth-page-section-wrapper  min-h-[100vh] h-full">
      <div className="custom-container">
        <div className="auth-page-wrapper-main pt-[73px] pb-[90px]">
          <div className="auth-page-brad-logo-box flex items-center justify-center"><Link href="/authentication" ><Image src="/images/icons/auth-page-brand-logo.svg" alt="brand logo image" width={204} height={46} /></Link></div>
          {children}
        </div>
      </div>
    </section>
  )
}
