import { Link, Image } from '@utils/packages'

export const metadata = {
  title: 'Authentications',
  description: 'Generated by create next app'
}

export default function AuthenticationLayout({ children }) {
  return (

    <section className='auth-page-section-wrapper  h-full min-h-[100vh]'>
      <div className='custom-container'>
        <div className='auth-page-wrapper-main pb-[90px] pt-[73px]'>
          <div className='auth-page-brad-logo-box flex items-center justify-center'>
            <Link href='/'>
              <Image
                src='/images/icons/auth-page-brand-logo.svg'
                alt='brand logo image'
                width={204}
                height={46}
              />
            </Link>
          </div>

          {children}
        </div>
      </div>
    </section>
  )
}
