import { Onest, Manrope } from 'next/font/google'
import '@/styles/globals.css'

const onest = Onest({ subsets: ['latin'], display: 'swap' })
const manrope = Manrope({ subsets: ['latin'], display: 'swap' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${onest.variable} ${manrope.variable}`}>
        {children}
      </body>
    </html>
  )
}
